#Here we calculate the difference between average and crystal

# mol load psf ../analysis_data/only_nucl_init.psf

mol load pdb ../analysis_data/only_nucl_init.pdb 
mol addfile ../analysis_data/only_nucl_average.pdb waitfor all

# mol addfile ../analysis_data/md_nucl.dcd step 10 waitfor all

proc rmsf_ref {selection first last ref} {

# frame ref is considered the reference one
$selection frame $ref
set ref_coord [$selection get { x y z } ]
set num_at [llength $ref_coord]




for {set i 0} {$i < $num_at} {incr i} {
set myrmsf($i) 0
}

for {set frame $first} {$frame <= $last} {incr frame} {
$selection frame $frame
set veclist [$selection get {x y z}]

 for {set i 0} {$i < $num_at} {incr i} {
 	set vec [lindex $veclist $i]
 	set vec_ref [lindex $ref_coord $i]
    set dx [expr [lindex $vec 0] - [lindex $vec_ref 0]]
    set dy [expr [lindex $vec 1] - [lindex $vec_ref 1]]
    set dz [expr [lindex $vec 2] - [lindex $vec_ref 2]]
	set myrmsf($i) [expr $myrmsf($i) + $dx * $dx + $dy * $dy + $dz * $dz ]
        }
puts $frame
}

 for {set i 0} {$i < $num_at} {incr i} {
lappend rmsf_temp [expr sqrt($myrmsf($i) / ($last - $first + 1)) ]

 	}


return $rmsf_temp
}


set all [atomselect top "all"]

set rmsf [rmsf_ref $all 1 1 0]
$all frame 1
$all set beta $rmsf
$all writepdb ../analysis_data/dif_av_cryst.pdb

#let's do some file output
set chains [list CHA CHE CHB CHF CHC CHG CHD CHH CHI CHJ]
set chains_names [list H3_1 H3_2 H4_1 H4_2 H2A_1 H2A_2 H2B_1 H2B_2 DNA_I DNA_J]


set outfile [open ../analysis_data/dif_av_cryst_chains.dat w]
puts $outfile "Deviations of CA and P atoms of nucleosome between crystal and MD average"
puts $outfile "Generated by VMD script"
puts $outfile "Residue ID"
puts $outfile "Deviation, A"


set ts "Resid"
foreach segname  $chains_names {
append ts "\t$segname"
}
puts $outfile $ts

for  { set i -73 } { $i<=150 } { incr i } {
set ds "$i"
foreach seg  $chains {

set sel [atomselect top "segname $seg and (name CA P)  and resid '$i'"]
if {[$sel num] == 0} { set beta 0
} else {
set  beta [$sel get beta]
}

append ds "\t$beta"

}
puts $outfile $ds
}

close $outfile 


#let's do some file output no for side chain averages
set chains [list CHA CHE CHB CHF CHC CHG CHD CHH CHI CHJ]
set chains_names [list H3_1 H3_2 H4_1 H4_2 H2A_1 H2A_2 H2B_1 H2B_2 DNA_I DNA_J]


set outfile [open ../analysis_data/dif_av_cryst_chains_sch.dat w]
puts $outfile "Deviations for side chains and bases of nucleosome between crystal and MD average"
puts $outfile "Generated by VMD script"
puts $outfile "Residue ID"
puts $outfile "Deviation, A"


set ts "Resid"
foreach segname  $chains_names {
append ts "\t$segname"
}
puts $outfile $ts

for  { set i -73 } { $i<=150 } { incr i } {
set ds "$i"
foreach seg  $chains {

set sel [atomselect top "segname $seg and (not backbone) and (not name P O1P O2P O3' O5' C5' C1' C2' C3' C4' O4') and resid '$i' and noh"]
if {[$sel num] == 0} { set mean 0
} else {
set  beta [$sel get beta]
set bl [llength $beta]
set mean 0
for {set j 0} { $j<$bl } { incr j } {
set mean [expr $mean + [lindex $beta $j]]
}
set mean [expr $mean / $bl]
}

append ds "\t$mean"

}
puts $outfile $ds
}
# set alpha_core_ca "((segname CHA CHE and (resid 64 to 78 or resid 86 to 114 or resid 121 to 131)) or (segname CHB CHF and (resid 31 to 41 or resid 49 to 76 or resid 83 to 93))  or (segname CHC CHG and (resid 27 to 37 or resid 45 to 73 or resid 80 to 89)) or (segname CHD CHH and (resid 34 to 45 or resid 53 to 81 or resid 88 to 98))) and name CA"
 
# set h3 [atomselect top "(segname CHA CHE and (resid 64 to 78 or resid 86 to 114 or resid 121 to 131)) and name CA"]

# #set h3_0 [atomselect top "(segname CHA CHE and (resid 64 to 78 or resid 86 to 114 or resid 121 to 131)) and name CA" frame 0]


#  set nframes [expr  [molinfo top get numframes] - 1 ]


#  set outfile [open ../analysis_data/max_rmsf.dat w]	
# # #set sel1 [atomselect top "segname CHI and resid '$r1'" frame $i]


# }
# puts -nonewline $outfile "\n"
# for { set i 1 } { $i<=$nframes } { incr i } {
# #set time [expr 0.1 * $i]
# #puts -nonewline $outfile [format "%.3f" "$time"]
# #puts  [format "Time %.3f" "$time"]
# # for { set r1 -73 } { $r1<=73 } { incr r1 } {
# # set sel1 [atomselect top "protein and noh" frame $i]
# # set r2 [expr $r1 * (-1)]
# # set sel2 [atomselect top "((segname CHI and resid '$r1') or (segname CHJ and resid '$r2')) and noh" frame $i]
# # set contacts [lindex [measure contacts  3.0 $sel1 $sel2] 1]

# foreach ind [$h3 get index] {

# set sel0 [atomselect top "index $ind" frame 0]
# set seli [atomselect top "index $ind" frame $i]

# set c0 [lindex [$sel0 get {x y z}] 0]
# set c1 [lindex [$seli get {x y z}] 0]

# set d [veclength [vecsub $c0 $c1]]
# #puts "KUKU"
# puts $outfile "$d"

# $sel0 delete
# $seli delete
# }



# # set nc [llength $contacts]
# # #puts "$contacts"
# # #puts [format "Check: %d" "$delta"]
# # puts -nonewline $outfile "\t$nc"

# # $sel2 delete
# # $sel1 delete
# # #hbonds -sel1 $sel1 -sel2 $sel2 -dist 3.0 -ang 30 -frames $i:$i -writefile yes -outfile ../analysis_data/dna_hbonds.dat
# # #-type unique -writefile yes -outfile ../analysis_data/dna_hbonds.dat

# # }
# #puts $outfile "\t$ralpha_core_ca\t$rh3\t$rh4\t$rh2a\t$rh2b\t$rh3_1\t$rh3_2\t$rh4_1\t$rh4_2\t$rh2a_1\t$rh2a_2\t$rh2b_1\t$rh2b_2\t$rdnai\t$rdnaj"
# }

 close $outfile 

#hbonds -sel1 $chi -sel2 $chj -dist 3.0 -ang 30 -type unique -writefile yes -outfile ../analysis_data/dna_hbonds.dat

exit


